version: "3.8"

services:
  # sid_mysql:
  #   container_name: sid_mysql
  #   image: mysql:8
  #   command:
  #     - --authentication_policy=*,,
  #     - --binlog-expire-logs-seconds=86400 # 1 days (1*24*60*60)
  #     - --host_cache_size=0
  #     - --pid-file=/var/lib/mysql/mysqld.pid
  #     - --default-authentication-plugin=mysql_native_password
  #   restart: unless-stopped
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - sid_network
  #   volumes:
  #     - type: volume
  #       source: mysql_db
  #       target: /var/lib/mysql
  #     - type: bind
  #       source: /var/lib/mysql
  #       target: /var/lib/mysql
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: 5m
  #       max-file: 5
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: admin
  #     MYSQL_DATABASE: sid
  #   healthcheck:
  #     test: ["CMD-SHELL", "mysql --user=admin --password=admin --execute 'SELECT 1;'"]
  #     interval: 3s
  #     timeout: 10s
  #     retries: 3

  php-web:
    container_name: php_web
    restart: unless-stopped
    image: php:7.0-apache
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 80:80
    # networks:
    #   - sid_network
    volumes:
      - ./www:/var/www/html
      - ./conf/apache.conf:/etc/apache2/sites-enabled
    environment:
      - ALLOW_OVERRIDE=true
    # depends_on:
    #   sid_mysql:
    #     condition: service_healthy
    command: "/bin/sh -c 'docker-php-ext-install mysqli && a2enmod rewrite && exec apache2-foreground '"

  # adminer:
  #   image: adminer:4
  #   container_name: adminer
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - sid_network
  #   depends_on:
  #     sid_mysql:
  #       condition: service_healthy
# networks:
#   sid_network:
#     name: sid_network
# volumes:
#   mysql_db:

# nginx:
#     image: nginx
#     container_name: nginx
#     ports:
#        - "80:80"
#     volumes:
#        - ./www:/var/www/html/
#        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#        - php-httpd

# https://github.com/abhishek70/docker-linux-codeigniter-mysql/tree/master
